config/routes.rb
Rails.application.routes.draw do

  # mount_ember_app :frontend, to: "/"

  namespace :api do
    namespace :v1 do
      resources :users, :defaults => { :format => 'json' }
      resources :locations, :defaults => { :format => 'json' }
    end
  end

  resources :locations
  resources :clues
  resources :users
  resources :games
  namespace :admin do
    resources :users
  end

  root to: "homepage#index"

  # get '/creative' => 'creatives#creative'
  get 'signup' => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  post 'score' => 'locations#score'
  get '/startlocation' => 'locations#create'
  get '/won' => 'games#won'
  get '/continue' => 'locations#continue'
  get '/chart' => 'admins#chart_info'

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
      <a class="navbar-brand" id="logo-text" href="/">Geogamer</a>
    </div>
    <!--  -->

    <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geogamer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Meddon|IM+Fell+English' rel='stylesheet' type='text/css'>
</head>
<body style="background-image:url('http://images.fineartamerica.com/images-medium-large-5/map-of-the-world-map-sepia-watercolor-michael-tompsett.jpg')">

  <%= render :partial => 'layouts/header' %>
  <%= yield %>

</body>
</html>